export enum EnvVariableConstant {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  ALLOWED_ORIGINS = 'ALLOWED_ORIGINS',
  ENABLE_DOCUMENTATION = 'ENABLE_DOCUMENTATION',
}
